services:

    App\Shared\Infrastructure\Controllers\ErrorController:
        tags: ['controller.service_arguments']
    
    App\User\Infrastructure\sql\:
        resource: '../src/User/Infrastructure/sql/*'
        autowire: true
        autoconfigure: true

    App\User\Application\:
        resource: '../src/User/Application/*'
        tags: ['controller.service_arguments']
        arguments:
            $userRepository: '@App\User\Infrastructure\sql\UserRepository'

    App\User\Infrastructure\Controller\:
        resource: '../src/User/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
            $userService: '@App\User\Application\UserService'
    
    App\Product\Infrastructure\sql\:
        resource: '../src/Product/Infrastructure/sql/*'
        autowire: true
        autoconfigure: true

    App\Product\Application\:
        resource: '../src/Product/Application/*'
        tags: ['controller.service_arguments']
        arguments:
            $productRepository: '@App\Product\Infrastructure\sql\ProductRepository'

    App\Product\Infrastructure\Controller\:
        resource: '../src/Product/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
            $productService: '@App\Product\Application\ProductService'
    
    
    
    App\Auth\Infrastructure\Repository\:
        resource: '../src/Auth/Infrastructure/Repository/*'
        autowire: true
        autoconfigure: true

    App\Auth\Application\:
        resource: '../src/Auth/Application/*'
        tags: ['controller.service_arguments']
        arguments:
            $userService: '@App\User\Application\UserService'
            $authRepository: '@App\Auth\Infrastructure\Repository\AuthRepository'

    App\Auth\Infrastructure\Controller\:
        resource: '../src/Auth/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
            $authService: '@App\Auth\Application\AuthService'