
services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/**/Entity/'
            - '../src/Kernel.php'
    
    ## USER
    App\User\Application\:
        resource: '../src/User/Application/*'
        tags: ['controller.service_arguments']
        arguments:
            $userRepository: '@App\User\Infrastructure\sql\UserRepository'

    App\User\Infrastructure\Controller\:
        resource: '../src/User/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
            $userService: '@App\User\Application\UserService'
    
    ## PRODUCT
    App\Product\Application\:
        resource: '../src/Product/Application/*'
        tags: ['controller.service_arguments']
        arguments:
            $productRepository: '@App\Product\Infrastructure\sql\ProductRepository'

    App\Product\Infrastructure\Controller\:
        resource: '../src/Product/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
            $productService: '@App\Product\Application\ProductService'
    
    ## AUTH
    App\Auth\Application\:
        resource: '../src/Auth/Application/*'
        tags: ['controller.service_arguments']
        arguments:
            $userService: '@App\User\Application\UserService'
            $authRepository: '@App\Auth\Infrastructure\Repository\AuthRepository'

    App\Auth\Infrastructure\Controller\:
        resource: '../src/Auth/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
        arguments:
            $authService: '@App\Auth\Application\AuthService'